CREATE TABLE `users` (
`id` INT(25) UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
`email` VARCHAR(255) NOT NULL , 
`username` VARCHAR(65) NOT NULL ,
`name` VARCHAR(65) NOT NULL ,
`role` TINYINT(1) DEFAULT 0 ,
`verified` TINYINT(1) DEFAULT 0 ,
`created` DATETIME NOT NULL ,
`updated` DATETIME NOT NULL ,
`password` VARCHAR(30) NOT NULL ,
`salt` VARCHAR(30) NOT NULL ,
`code` VARCHAR(30) NOT NULL
);